name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Setup SSH agent (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV

      - name: Setup SSH agent (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Ensure OpenSSH is available
          if (Get-WindowsCapability -Online | Where-Object Name -like "OpenSSH.Client*" | Where-Object State -eq "NotPresent") {
            Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
          }

          # Start ssh-agent service
          try {
            Set-Service ssh-agent -StartupType Manual -ErrorAction SilentlyContinue
            Start-Service ssh-agent -ErrorAction Stop
            Write-Host "SSH agent service started successfully"
            
            # Wait a moment for the service to be fully ready
            Start-Sleep -Seconds 2
            
            # Set SSH_AUTH_SOCK environment variable
            $env:SSH_AUTH_SOCK = "\\.\pipe\openssh-ssh-agent"
            echo "SSH_AUTH_SOCK=$env:SSH_AUTH_SOCK" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            Write-Host "Set SSH_AUTH_SOCK to: $env:SSH_AUTH_SOCK"
            
            # Test SSH agent connectivity
            try {
              $testResult = ssh-add -l 2>&1
              Write-Host "SSH agent test result: $testResult"
            } catch {
              Write-Host "SSH agent connectivity test failed: $($_.Exception.Message)"
            }
            
          } catch {
            Write-Host "Failed to start ssh-agent service: $($_.Exception.Message)"
            Write-Host "Trying alternative approach with process startup"
            
            # Alternative: Start ssh-agent as a process and capture output
            $sshAgentOutput = ssh-agent
            Write-Host "SSH agent output: $sshAgentOutput"
            
            # Parse the output to set environment variables
            if ($sshAgentOutput -match "SSH_AUTH_SOCK=([^;]+)") {
              $sshAuthSock = $matches[1]
              $env:SSH_AUTH_SOCK = $sshAuthSock
              echo "SSH_AUTH_SOCK=$sshAuthSock" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
              Write-Host "Set SSH_AUTH_SOCK to: $sshAuthSock"
            }
            
            if ($sshAgentOutput -match "SSH_AGENT_PID=([^;]+)") {
              $sshAgentPid = $matches[1]
              $env:SSH_AGENT_PID = $sshAgentPid
              echo "SSH_AGENT_PID=$sshAgentPid" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
              Write-Host "Set SSH_AGENT_PID to: $sshAgentPid"
            }
          }

          # Add Git's SSH tools to PATH
          $gitSshPath = "C:\Program Files\Git\usr\bin"
          if (Test-Path $gitSshPath) {
            echo $gitSshPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            Write-Host "Added Git SSH tools to PATH: $gitSshPath"
          }

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run comprehensive platform tests
        run: cargo test --test comprehensive_platform_tests -- --nocapture
